apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: slurm-compute
spec:
  selector:
    matchLabels:
      name: slurm-compute 
  template:
    metadata:
      labels:
        name: slurm-compute 
        service: slurm
    spec:
      nodeSelector: 
        type: slurm-compute
      containers:
      - image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["slurmd"]
        imagePullPolicy: Always
        name: slurmd
        ports:
        resources: {}
        volumeMounts:
        - mountPath: /root/hostname
          name: localhost-name
          readOnly: true
      - image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["munged"]
        imagePullPolicy: Always
        name: munged
        ports:
        resources: {}
#        volumeMounts:
#        - mountPath: /etc/munge
#          name: localhost-name
#          readOnly: true
      volumes:
        - name: localhost-name 
          hostPath:
          # directory location on host
            path: /etc/hostname
            type: File
      serviceAccount: default
      terminationGracePeriodSeconds: 10
