apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: slurm-compute
spec:
  selector:
    matchLabels:
      name: slurm-compute 
  template:
    metadata:
      labels:
        name: slurm-compute 
        service: slurm
    spec:
      nodeSelector: 
        type: slurm-compute
      containers:
      - image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["slurmd"]
        imagePullPolicy: Always
        #lifecycle:
        #  postStart:
        #    exec:
        #      command: ["chown", "slurm:slurm", "/etc/slurm"]
        name: slurmd
        ports:
        resources: {}
        volumeMounts:
        - mountPath: /root/hostname
          name: localhost-name
          readOnly: true
        - mountPath: /var/run/munge
          name: run-munge
        - mountPath: /root/hosts
          name: host-mappings
        - mountPath: /etc/slurm-llnl
          name: etc-slurm
          readOnly: true
        - mountPath: /var/lib/extrausers
          name: extra-users
          readOnly: true
      - image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["munged"]
        imagePullPolicy: Always
        name: munged
        ports:
        resources: {}
        volumeMounts:
        - mountPath: /var/run/munge
          name: run-munge
        - mountPath: /local/munge-key
          name: munge-key
        - mountPath: /var/lib/extrausers
          name: extra-users
          readOnly: true
      serviceAccount: default
      volumes:
      - name: munge-key
        secret:
          secretName: munge-key
      - name: etc-slurm
        configMap:
          #mode: 0555
          defaultMode: 0555
          name: slurm-node-conf
      - name: host-mappings
        configMap:
          name: host-mappings
      - name: localhost-name
        hostPath:
          path: /etc/hostname
          type: File
      - name: run-munge
        emptyDir: {}
      - name: extra-users
        configMap:
          name: extrausers
          defaultMode: 0555
      terminationGracePeriodSeconds: 10
