apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: slurmcontroller
  name: slurmcontroller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: slurmcontroller
    spec:
      containers:
      - args:
        - slurmdbd
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["slurmdbd"]
        image: willthelaw/slurm-docker-ubuntu:latest
        name: slurmdbd
        resources: {}
        volumeMounts:
        - mountPath: /etc/slurm-llnl
          name: etc-slurm
        - mountPath: /var/log/slurm
          name: var-log-slurm
      - args:
        - slurmctld
        image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["slurmctld"]
        name: slurmctld
        resources: {}
        volumeMounts:
        - mountPath: /etc/slurm-llnl
          name: etc-slurm
        - mountPath: /data
          name: slurm-jobdir
        - mountPath: /var/log/slurm
          name: var-log-slurm
        - mountPath: /etc/munge
          name: etc-munge
      - args:
        - munged
        image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["munged"]
        name: munged
        resources: {}
        volumeMounts:
        - mountPath: /etc/munge
          name: etc-munge
      hostname: slurmcontroller
      restartPolicy: Always
      volumes:
      - name: etc-munge
        persistentVolumeClaim:
          claimName: etc-munge
      - name: etc-slurm
        persistentVolumeClaim:
          claimName: etc-slurm
      - name: var-log-slurm
        persistentVolumeClaim:
          claimName: var-log-slurm
      - name: slurm-jobdir
        persistentVolumeClaim:
          claimName: slurm-jobdir
status: {}
