apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: slurmcontroller
  name: slurmcontroller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: slurmcontroller
    spec:
      containers:
      - args:
        - slurmdbd
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["slurmdbd"]
        image: willthelaw/slurm-docker-ubuntu:latest
        name: slurmdbd
        resources: {}
        volumeMounts:
        - mountPath: /etc/slurm-llnl
          name: etc-slurm
        - mountPath: /var/log/slurm
          name: var-log-slurm
        - mountPath: /var/run/munge
          name: run-munge
      - args:
        - slurmctld
        image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["slurmctld"]
        name: slurmctld
        resources: {}
        volumeMounts:
        - mountPath: /etc/slurm-llnl
          name: etc-slurm
        - mountPath: /data
          name: slurm-jobdir
        - mountPath: /var/log/slurm
          name: var-log-slurm
        - mountPath: /var/run/munge
          name: run-munge
      - args:
        - munged
        image: willthelaw/slurm-docker-ubuntu:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["munged"]
        name: munged
        resources: {}
        volumeMounts:
        - mountPath: /local/munge-key
          name: munge-key
        - mountPath: /var/run/munge
          name: run-munge
      hostname: slurmcontroller
      restartPolicy: Always
      volumes:
      - name: munge-key
        secret:
          secretName: munge-key
      - name: etc-slurm
        configMap:
          name: slurm-conf
#      - name: etc-munge
#        persistentVolumeClaim:
#          claimName: etc-munge
      - name: run-munge
        emptyDir: {}
#      - name: etc-slurm
#        persistentVolumeClaim:
#          claimName: etc-slurm
      - name: var-log-slurm
        persistentVolumeClaim:
          claimName: var-log-slurm
      - name: slurm-jobdir
        persistentVolumeClaim:
          claimName: slurm-jobdir
status: {}
