kind: Service
apiVersion: v1
metadata:
  labels:
    io.kompose.service: slurm-mysql
  name: slurm-mysql
spec:
  selector:
    io.kompose.service: slurm-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
